name: Bitsong

on:
  schedule:
    - cron: '0 */1 * * *'   # Every 2 hours
  workflow_dispatch:         # Manual trigger

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Install system dependencies
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb

      # Step 3: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Step 4: Setup Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Step 5: Install dependencies in Bitsong folder
      - name: Install Bitsong dependencies
        working-directory: Bitsong
        run: |
          npm install playwright
          npx playwright install firefox
          python -m pip install --upgrade pip
          python -m pip install requests

      # Step 6: Run runner.js with Xvfb inside Bitsong
      - name: Run Bitsong runner.js with Xvfb
        working-directory: Bitsong
        run: |
          xvfb-run -a node runner.js

      # Step 7: Store Bitsong outputs (JSON only) as artifacts
      - name: Upload Bitsong results
        uses: actions/upload-artifact@v4
        with:
          name: bitsong-output
          path: |
            Bitsong/tempmail.json
          retention-days: 7
