name: tester2

on:
  schedule:
    - cron: '0 */1 * * *'   # Every 2 hours
  workflow_dispatch:         # Manual trigger

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Engine dependencies
        working-directory: engine
        run: |
          npm install playwright
          npx playwright install firefox
          python -m pip install --upgrade pip
          python -m pip install requests

      - name: Run Engine runner2.js with Xvfb
        working-directory: engine
        run: |
          xvfb-run -a node runner2.js

      - name: Commit and push Engine results
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git checkout main
          git fetch origin main
          git pull --rebase origin main || true

          git add engine/tempmail_4.json \
                  engine/tempmail_5.json \
                  engine/tempmail_6.json \
                  engine/tempmail_7.json \
                  engine/*.png

          git commit -m "Update Engine results [auto]" || echo "No changes to commit"
          git push --force-with-lease origin main